plugins {
	id 'org.igniterealtime.smack.java-common-conventions'
	id 'com.diffplug.spotless' version '6.25.0'
	id 'io.github.cosmicsilence.scalafix' version '0.2.9'
}

description = """\
A REPL (Read-Eval-Print-Loop) for Smack, or, in other words, a CLI (Command Line Interface) for Smack."""

apply plugin: 'scala'

ext {
    scalaVersion = '3.3.7'
}

dependencies {
    api project(':smack-examples')

    implementation "org.scala-lang:scala3-library_3:$scalaVersion"
    implementation "com.lihaoyi:ammonite_$scalaVersion:3.0.9"
}

task printClasspath(dependsOn: assemble) {
    doLast {
        println sourceSets.main.runtimeClasspath.asPath
    }
}

spotless {
    scala {
        scalafmt('3.7.17').configFile(rootProject.file('.scalafmt.conf'))
    }
}
