rules = [
  DisableSyntax
]

DisableSyntax {
  noReturns = true
  noNulls = true
  noFinalize = true
  noAsInstanceOf = true
  noIsInstanceOf = true
  regex = [
    {
      id = "println"
      pattern = "println"
      message = "Use logging instead of println"
    }
  ]
}
